version: "3.7"
services:
  myanimearchive:
    build: './myanimearchive'
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
    environment:
      - PYTHONBUFFERED=true
      - FLASK_DEBUG=1
    env_file:
      - .env
    volumes:
      - ./myanimearchive:/app
    command: python app.py
    restart: on-failure
  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"
  celery_workers:
    build: './celery_workers'
    user: nobody
    env_file:
      - .env
    depends_on:
      - rabbit
      - myanimearchive
    restart: always